### ISSUE TITLE
[Miner] - Refactor Miner to use baseminer approach

### ISSUE THREAD

**Issue by aph5nt** [blockchain-insights/blockchain-data-subnet#17]
Problem: Current solution is not unit test friendly and it has high complexity,

Solution: Take inspiration from : https://github.com/bittranslateio/bittranslate/tree/main/neurons/miners/baseminer, refactor miner code, add unit tests

**Comment by 0xMarx** [comment]
This will be solved by integrating the new bittensor-subnet-template 

Integration is in development and should be done by 31.01.2024
