### ISSUE TITLE
[Validator] -  Setting weights across restarts and nodes validator talked to

### ISSUE THREAD

**Issue by aph5nt** [blockchain-insights/blockchain-data-subnet#18]
VIA SciFantastic and floppyfish [τ, τ]

1) set weights for nodes that you have talked to
2) persist weights across restarts, so you don't lose all state.

(https://discord.com/channels/799672011265015819/1161764869280903240/1175874298402058350)

SciFantastic — Dziś o 20:09
Looks like process_weights_for_netuid already does a nice elimination of 0 weights, so maybe doing #1 is easier than I thought. I think it'd be like @floppyfish [τ, τ] suggested, which is mking sure the weights are initially 0, and then we only touch weights of nodes we talk to, and the 0's will be filtered out.
Obraz

**Comment by aph5nt** [comment]
https://github.com/gitphantomman/scraping_subnet/pull/54/files

**Comment by 0xMarx** [comment]
This will be fixed by the integration of the new bittensor-subnet-template. Should be done by 31.01.2024
